### PR TITLE
Fixed: click on card to open detail page from upload page (#209)

### LINKED ISSUE #209: Enable Click Anywhere on Card to Open Detail Page on Upload Page
## Current behavior
Currently, on the Upload page, users are required to click on specific texts within a card to navigate to the detail page. This interaction pattern might be cumbersome for users, especially on smaller devices or touchscreens. 

## Expected behavior
Implement a modification in the Upload page component to allow users to click anywhere on a card to navigate to the corresponding detail page.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by shanmukhdutt**
Closes #209 

### Contribution and Currently Important Rules Acceptance

- [ ] I have read and followed [contribution rules](https://github.com/hotwax/inventory-count#contribution-guideline)

### CODE REVIEW

**Review by k2maan — APPROVED** [review]

**Review by ymaheshwari1 — APPROVED** [review]

File: src/views/Upload.vue [hunk 1]
```diff
@@ -7,7 +7,7 @@
     </ion-header>
 
     <ion-content>
-      <ion-card v-for="product in uploadProducts" :key="product.productId">
+      <ion-card v-for="product in uploadProducts" :key="product.productId" @click="viewProduct(product)">
```
Comment (ymaheshwari1) [inline src/views/Upload.vue:10]: Remove the click event from ion-label, as we have added the event on the card itself.

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]

**Review by ymaheshwari1 — APPROVED** [review]
