### PR TITLE
Fixed: When calling getPermissions api duplicate permissionIds are passed in the payload(#211)

### LINKED ISSUE #211: When calling getPermissions api duplicate permissionIds are passed in the payload
## Current behavior

In the getPermissions api, duplicate permission keys are passed in the payload that is unnecessary

## Expected behavior

Pass only the unique permissionIds in the api call

## Steps to reproduce the issue

1. Login into any app
2. Inspect the network and check on the `getPermissions` api call
3. Check that the same id is passed multiple times in the payload

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by shanmukhdutt**
### Related Issues

Closes #211 

### Contribution and Currently Important Rules Acceptance

- [ ] I have read and followed [contribution rules](https://github.com/hotwax/inventory-count#contribution-guideline)

### CODE REVIEW

File: src/store/modules/user/actions.ts [hunk 1]
```diff
@@ -31,7 +31,9 @@ const actions: ActionTree<UserState, RootState> = {
       const permissionId = process.env.VUE_APP_PERMISSION_ID;
       // Prepare permissions list
       const serverPermissionsFromRules = getServerPermissionsFromRules();
-      if (permissionId) serverPermissionsFromRules.push(permissionId);
+      
+      const removeDuplicatePermissionIds = new Set(serverPermissionsFromRules)
+      removeDuplicatePermissionIds.add(permissionId);
 
       const serverPermissions = await UserService.getUserPermissions({
         permissionIds: serverPermissionsFromRules
```
Comment (ymaheshwari1) [inline src/store/modules/user/actions.ts:39]: We can remove the above code to create set.
```suggestion
        permissionIds: [...new Set(serverPermissionsFromRules)]
```

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]
