### PR TITLE
Fixed: Product data not fetched on refresh (#85zrvh9we)

### LINKED ISSUE #165: Data not fetched when we refresh the product detail page
## Current behavior
When we go on the product detail page to input the inventory count and refresh the page, the data is not fetched. It still allows to input inventory and save it to the upload list but it does not display any product details.

## Expected behavior
Refresh function should work and after refresh the product details should be visible. 

## Steps to reproduce the issue
-Login into the inventory count app.
- Search for a product and go to the product detail page.
- Refresh the page.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by k2maan**
### Related Issues

Closes #165 

### Screenshots of Visual Changes before/after (If There Are Any)

[Screencast from 05-04-23 12:17:57 PM IST.webm](https://user-images.githubusercontent.com/59442907/230002591-72b3c157-1eaf-479a-8d78-db9747a41eb4.webm)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)
- [ ] I have changed the target to hacktoberfest branch

### CODE REVIEW

File: src/App.vue [hunk 1]
```diff
@@ -72,14 +72,15 @@ export default defineComponent({
...
     emitter.on('dismissLoader', this.dismissLoader);
-
+  },
+  created() {
     initialise({
       token: this.userToken,
       instanceUrl: this.instanceUrl,
       cacheMaxAge: this.maxAge,
       events: {
         unauthorised: this.unauthorized,
```
Comment (ymaheshwari1) [inline src/App.vue:82]:
```suggestion
        unauthorised: this.unauthorised,
```

**Review by ymaheshwari1 — CHANGES_REQUESTED** [review]

File: src/App.vue (hunk 1 above)
Comment (k2maan) [reply src/App.vue]: Updated sir

**Review by ymaheshwari1 — APPROVED** [review]

**Review by adityasharma7 — APPROVED** [review]
